version: "3.9" 
services:
    serv1:
        build: .
        ports:
            - "3000:3000"
            - "3333:3333"
        env_file:
            - .docker.env
        environment:
            REACT_URL: "http://localhost:3333"