version: "3.9" 
services:
    library-center:
        build: .
        ports:
            - "3000:3000"
        env_file:
            - ./.env
        environment:
            - REACT_APP_URL=http://localhost:8080
            - CHOKIDAR_USEPOLLING=true
      
            