

FROM node:alpine as build
WORKDIR /my-app/src
COPY package.json ./
COPY package-lock.json ./
RUN npm i
RUN npm run build
COPY ./ ./
CMD ["npm run start"]


FROM nginx
COPY --from=build /my-app/src/build /usr/share/nginx/html
